### PR TITLE
Add clang-win to appveyor

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by Lastique** [comment]
I can see the build is failing but I can't see the command line arguments as they are hidden in the .rsp file. As I suggested in https://github.com/boostorg/log/pull/91#issuecomment-535414676, please investigate the cause on your end. Are the missing libraries specified in the .rsp file? If yes then please report the bug to the clang-win developers. If not or the command line options are incorrect then report the problem to [Boost.Build](https://github.com/boostorg/build/issues/new).

As the PR is failing and I'm not planning to add workarounds for this compiler in Boost.Log, I'm going to close the PR, sorry.

**Comment by pdimov** [comment]
The issue in clang-win.jam has been fixed in https://github.com/boostorg/build/commit/2c00d909f4f6c6faf7dce3d7359376e5fe753d67 on develop, but the fix is not on master yet.

**Comment by Lastique** [comment]
Yeah, well, I just recently had to disable it for Boost.Filesystem because of missing some mspdb.dll error or something like that. I'm done with clang-win for now.

**Comment by pdimov** [comment]
The missing mspdbcore.dll error is only on address-model=32, so I restricted my clang-win Appveyor jobs to 64 bit instead of removing them entirely.

**Pull request closed without merging**
