### PR TITLE
Use BOOST_OVERRIDE to fix GCC -Wsuggest-override and Clang-tidy moder…

### PR DESCRIPTION
**Pull request by EugeneZelenko**
…nize-use-override warnings.

### CODE REVIEW

**Comment by Lastique** [comment]
Destructors don't need to be marked.

**Comment by EugeneZelenko** [comment]
Somehow GCC -Wsuggest-override doesn't cover destructors, but Clang-tidy modernize-use-override warnings does.

Anyway destructors are not different from methods in respect to `virtual/override/final`.

**Comment by Lastique** [comment]
They are different in that they always override if the base destructor is virtual. The problem with the markup is that it *requires* the base destructor to be virtual, which can be a problem if this changes at some point.

**Comment by EugeneZelenko** [comment]
Same would happen with methods.

**Comment by EugeneZelenko** [comment]
Thank you for help!

**Pull request merged**
